# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

name: "Techlore"
title: "Techlore — a safer internet."
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Techlore is educating people about digital rights, privacy, security, 
  digital control, and other important topics to push the world towards a safer internet.
baseurl: "/techlore" # the subpath of your site, e.g. /blog
url: "https://michalsvatos.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# -----------------------------------------
# Global links
#
techloreVideos:
  links:
    peertube: "https://neat.tube/c/techlore/videos?sort=-originallyPublishedAt"
    youtube: "https://www.youtube.com/@techlore"
techloreClips:
  links:
    youtube: "https://www.youtube.com/@techloreclips"
surveillanceReport:
  links:
    web: "https://www.surveillancereport.tech/"
    rss: "https://feeds.acast.com/public/shows/65e15188b8456c00169f4864"
    peertube: "https://apertatube.net/c/surveillancereport/videos"
    youtube: "https://www.youtube.com/@SurveillanceReport"
goincognito:
  links:
    premium: "https://techlore.teachable.com/p/go-incognito"
support:
  links:
    patreon: "https://www.patreon.com/techlore"
    librapay: "https://liberapay.com/Techlore/"
    paypal: "https://www.paypal.com/donate?hosted_button_id=B3GU7WNGBGQ4J"
    kofi: "https://ko-fi.com/techlore"
socials:
  links:
    mastodon: "https://social.lol/@techlore"
    twitter: "https://twitter.com/TechloreInc"
    reddit: "https://www.reddit.com/r/techlore/"
    matrix: "https://matrix.to/#/%23techlore:matrix.org"
    telegram: "https://t.me/techlorefeed"
forum:
  links:
    discuss: "https://discuss.techlore.tech/"

# Build settings
#theme: minima
plugins:
  - jekyll-seo-tag
#  - jekyll-feed

sass:
  sass_dir: _sass
  style: compressed

collections:
  videos:
    output: true
  clips:
    output: true
    permalink: /clips/:name
  goincognito:
    output: true
    permalink: /goincognito/:name
  surveillance-report:
    output: true
    permalink: /surveillance-report/:name
  techlore:
    output: true
    permalink: /techlore/:name
  guides:
    output: true
    permalink: /guides/:name
collections_dir: videos

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
